# https://goreleaser.com/customization/

before:
  hooks:
    - go mod tidy

# https://goreleaser.com/customization/build/
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    # GOOS list to build for.
    # For more info refer to: https://go.dev/doc/install/source#environment
    # Defaults are darwin and linux.
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - arm64

# https://goreleaser.com/customization/archive/
archives:
  - id: default
    builds:
      - default
    wrap_in_directory: true
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

# https://goreleaser.com/customization/snapshots/
snapshot:
  name_template: '{{ incpatch .Version }}-dev-{{.ShortCommit}}'

# https://goreleaser.com/customization/checksum/
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

# https://goreleaser.com/customization/release/
release:
  prerelease: true
  draft: true
  
